const finishedBooks = [
  {
    id: 1,
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    year: 1960,
    isComplete: true,
  },
  {
    id: 2,
    title: '1984',
    author: 'George Orwell',
    year: 1949,
    isComplete: true,
  },
  {
    id: 3,
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    year: 1925,
    isComplete: true,
  },
  {
    id: 4,
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    year: 1813,
    isComplete: true,
  },
  {
    id: 5,
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    year: 1951,
    isComplete: true,
  },
  {
    id: 6,
    title: 'To the Lighthouse',
    author: 'Virginia Woolf',
    year: 1927,
    isComplete: true,
  },
  {
    id: 7,
    title: 'The Bell Jar',
    author: 'Sylvia Plath',
    year: 1963,
    isComplete: true,
  },
  {
    id: 8,
    title: 'Moby-Dick',
    author: 'Herman Melville',
    year: 1851,
    isComplete: true,
  },
  {
    id: 9,
    title: 'Beloved',
    author: 'Toni Morrison',
    year: 1987,
    isComplete: true,
  },
  {
    id: 10,
    title: 'Frankenstein',
    author: 'Mary Shelley',
    year: 1818,
    isComplete: true,
  },
];

const unfinishedBooks = [
  {
    id: 11,
    title: 'War and Peace',
    author: 'Leo Tolstoy',
    year: 1869,
    isComplete: false,
  },
  {
    id: 12,
    title: 'The Odyssey',
    author: 'Homer',
    year: 800,
    isComplete: false,
  },
  {
    id: 13,
    title: 'Don Quixote',
    author: 'Miguel de Cervantes',
    year: 1605,
    isComplete: false,
  },
  {
    id: 14,
    title: 'The Brothers Karamazov',
    author: 'Fyodor Dostoevsky',
    year: 1880,
    isComplete: false,
  },
  {
    id: 15,
    title: 'Middlemarch',
    author: 'George Eliot',
    year: 1871,
    isComplete: false,
  },
  {
    id: 16,
    title: 'The Sound and the Fury',
    author: 'William Faulkner',
    year: 1929,
    isComplete: false,
  },
  {
    id: 17,
    title: 'The Picture of Dorian Gray',
    author: 'Oscar Wilde',
    year: 1890,
    isComplete: false,
  },
  {
    id: 18,
    title: 'The Grapes of Wrath',
    author: 'John Steinbeck',
    year: 1939,
    isComplete: false,
  },
  {
    id: 19,
    title: 'Heart of Darkness',
    author: 'Joseph Conrad',
    year: 1899,
    isComplete: false,
  },
  {
    id: 20,
    title: 'Jane Eyre',
    author: 'Charlotte Brontë',
    year: 1847,
    isComplete: false,
  },
];

export { finishedBooks, unfinishedBooks };
